services:
  - type: web
    name: pvco-molecor-backend
    runtime: python
    rootDir: pvco-molecor-backend
    buildCommand: ./build.sh
    startCommand: gunicorn molecor_backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
